name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Coveralls
        run: npm install -g coveralls

      - name: Run Jest coverage
        run: npm run test:jest-coverage

      - name: Upload Jest coverage
        run: cat ./coverage/jest/lcov.info | coveralls --repo-token ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Run Mocha coverage
        run: npm run test:mocha-coverage

      - name: Upload Mocha coverage
        run: cat ./coverage/mocha/lcov.info | coveralls --repo-token ${{ secrets.COVERALLS_REPO_TOKEN }}